app/app.py
from flask import Flask
from .register import (blueprints,
                       extensions,
                       jinja_extensions,
                       logging_handler,
                       middleware)

def create_app(settings_override=None):
    """
    Create a Flask application using the app factory pattern.

    :param settings_override: Override settings
    :return: Flask app
    """
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py', silent=True)

    if settings_override:
        app.config.update(settings_override)

    blueprints(app)
    extensions(app)
    jinja_extensions(app)
    logging_handler(app)
    middleware(app)
    return app



app/blueprints/page/__init__.py
from .views import page

app/blueprints/page/views.py
from flask import Blueprint, render_template

from .contexts import PageHomeContext


page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    context = PageHomeContext()
    return render_template('page/home.jinja2', ctx=context)

app/blueprints/page/templates/page/home.jinja2
{# Base template #}
{% extends "layouts/base.jinja2" %}

{# Imports #}
{% import "macros/grid.jinja2" as grid %}

{# Variables #}
{% set title = _("Home") %} {# Page title #}
{% set description = _("") %} {# Page description (optional) #}

{# Heading #}
{% block heading %}
  <h3>Welcome to {{ config.APP_NAME }}'s homepage!</h3>
  <hr>
{% endblock %}

{# Body #}
{% block body %}
  {% call grid.row() %}
    {% call grid.col(12, 12) %}
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.

        Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
        cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum.
      </p>
    {% endcall %}
  {% endcall %}
{% endblock %}

app/templates/layouts/_base.jinja2
{% import "macros/flash.jinja2" as flash with context %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta name="description" contents="{{ description or _("No description available for this page.") }}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{- config.APP_NAME + " · " + title|e if title else config.APP_NAME -}}</title>
        {# Stylesheets #}
        {% block prevendor_css %}{% endblock %}
        {% include "styles/bootstrap.jinja2" %}
        {% include "styles/fontawesome.jinja2" %}
        {% block postvendor_css %}{% endblock %}
        {% include "styles/app.jinja2" %}
    </head>
    <body>
      <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for("page.home") }}">
              {{- config.APP_NAME -}}
            </a>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="{{ url_for("page.home") }}">{{ _("Home") }}</a>
            </li>
          </ul>
        </div>
      </nav>
      <main class="{% block container_type %}{% endblock %}">
        {{ flash.render() }}
        {% block heading %}{% endblock %}
        {% block body %}{% endblock %}
      </main>
      <footer class="footer text-center">
        <div class="container">
          <p class="footer-margin">{{ config.APP_NAME }} &copy; {{ get_year() }}</p>
        </div>
      </footer>
      {# Scripts #}
      {% block prevendor_scripts %}{% endblock %}
      {% include "scripts/jquery.jinja2" %}
      {% include "scripts/bootstrap.jinja2" %}
      {% block postvendor_scripts %}{% endblock %}
    </body>
</html>

app/templates/layouts/base.jinja2
{% extends "layouts/_base.jinja2" %}
{% block container_type %}container{% endblock %}

app/templates/layouts/fluid.jinja2
{% extends "layouts/_base.jinja2" %}
{% block container_type %}container-fluid{% endblock %}

app/templates/macros/flash.jinja2
{# Render Flask messages. #}
{%- macro render() -%}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      <div id="flash-messages" class="sm-margin-top">
        {% for category, msg in messages %}
          <div class="alert alert-{{ category }}" role="alert">
            {{ msg }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{%- endmacro -%}

app/templates/macros/form.jinja2
{# Render a form field's label with visual aid to see if it's required. #}
{%- macro field_label(field) -%}
    <label for="{{ field.id }}">
        {{- field.label.text }}{{ '*' if field.flags.required else '' -}}
    </label>
{%- endmacro -%}

{# Render a form field's errors. #}
{%- macro field_errors(f) -%}
    {% if f.errors %}
        <ul class="list-unstyled text-danger field-error">
            {% for error in f.errors %}
                <li>{{ error | e }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{%- endmacro -%}

{# Render a form field. #}
{%- macro field(f, field_class) -%}
    {% set field_class = 'form-control ' + field_class %}
    {{ f(class_=field_class, **kwargs) }}
{%- endmacro -%}

{# Render a checkbox field. #}
{%- macro checkbox_field(f, field_class) -%}
    {{ f(type='checkbox', class_=field_class, **kwargs) }} {{ f.label }}
{%- endmacro -%}

{# Render a file upload field. #}
{%- macro fileupload_field(f, field_class) -%}
    {{ f(type='file', class_=field_class, **kwargs) }} {{ f.label }}
{%- endmacro -%}

{# Render a Bootstrap 3 form group with errors for various field types. #}
{%- macro form_group(f, css_class='', field_class='') -%}
    {% if f.errors %}
        {% set css_class = css_class + ' has-error ' + kwargs.pop('class', '') %}
    {% endif %}
    {% if f.type == 'BooleanField' %}
        <div class="checkbox {{ css_class }}">
            {{ checkbox_field(f, field_class, **kwargs) }}
    {% else %}
        <div class="form-group {{ css_class }}">
            {{ field_label(f) }}
            {{ field(f, field_class, **kwargs) }}
    {% endif %}
            {{ field_errors(f) }}
            {{ caller () }}
        </div>
{%- endmacro %}

{# Render a form tag that contains a CSRF token and all hidden fields, it also
   properly supports all HTTP version, simply pass in method='delete', etc.. #}
{%- macro form_tag(form, endpoint, fid='', class='', method='post', enctype='application/x-www-form-urlencoded') -%}
    {% set method = method | lower %}
    <form id="{{ fid }}" action="{{ url_for(endpoint, **kwargs) }}"
          method="{{ method }}" enctype="{{ enctype }}" class="{{ class }}" role="form">
          {{ form.hidden_tag() }}
          {{ caller () }}
    </form>
{%- endmacro -%}

app/templates/macros/grid.jinja2
{# Renders a Bootstrap grid row.

  Args:
    css_class (str, optional): Space delimited CSS classes appended to the column div.

#}
{% macro row(css_class="") %}
  <div class="{{ "row {}".format(css_class) if css_class else "row" }}">
    {{ caller() }}
  </div>
{% endmacro %}


{# Renders a Bootstrap grid column.

  Args:
    md (int): The column width for desktop-sized viewports.
    xs (int): The column width for mobile-sized viewports.
    css_class (str, optional): Space delimited CSS classes appended to the column div.
    **kwargs: Additionnal integer typed keyword-arguments "lg" and/or "sm" can be
      provided for adding `col-lg-` or `col-sm-` column classes.

  Example:
    {% call col(6, 12) %}
      ...
    {% endcall %}

    Will render:
    <div class="col-md-6 col-xs-12">
      ...
    </div>

    Using `col` with "sm"/"lg":
    {% call col(6, 12, sm=12) %}
      ...
    {% endcall %}

    Will render:
    <div class="col-md-6 col-xs-12 col-sm-12">
      ...
    </div>

#}
{% macro col(md, xs, css_class="") %}
  {% set classes = ["col-md-{}".format(md), "col-xs-{}".format(xs)] %}
  {% if kwargs.lg %}{% set classes = ["col-lg-{}".format(kwargs.lg)] + classes %}{% endif %}
  {% if kwargs.sm %}{% set classes = classes + ["col-sm-{}".format(kwargs.sm)] %}{% endif %}
  {% set classes = classes + css_class.split() %}
  <div class="{{ " ".join(classes) }}">
    {{ caller() }}
  </div>
{% endmacro %}

app/templates/macros/panel.jinja2
{# Renders a Bootstrap panel with a title.

  Note:
    `caller` content is appended inside the panel body (using nested caller bugfix).

  Args:
    title (str, optional): The panel title.

#}
{% macro panel(title=None) -%}
    {% set content = caller() %}
    {{ panel_title(title) }}
    {% call panel_body() %}{{ content }}{% endcall %}
{%- endmacro %}


{# Renders a panel title.

  Note:
    This will render a non-breaking space if no title is provided.

  Args:
    title (str, optional): The panel title.

#}
{% macro panel_title(title=None) %}
  {% if title %}
    <h4>{{ title }}</h4>
  {% else %}
    <h4>&nbsp;</h4>
  {% endif %}
{% endmacro %}


{# Renders a Bootstrap panel.

  Note:
    `caller` content is appended inside the panel body.

#}
{% macro panel_body() %}
  <div class="panel panel-default">
    <div class="panel-body">
        {{ caller() }}
    </div>
  </div>
{% endmacro %}

app/templates/macros/table.jinja2
{% import "macros/utils.jinja2" as utils %}


{# Renders a responsive Bootstrap table.

  Args:
    attr(dict, optional): The HTML attributes applied to the table tag.
    css_class (str, optional): Space delimited CSS classes to append to the
      table tag.

  Example:
    {% call table(attr={"id": "table-id"}) %}
      {% call table_headers() %}...{% endcall %}
      {% call table_body() %}
        ...
      {% endcall %}
    {% endcall %}

#}
{% macro table(attr={}) %}
  <div class="table-responsive">
    <table {{ utils.attributes(attr, css_class="table") }}>
      {{ caller() }}
    </table>
  </div>
{% endmacro %}


{# Renders the HTML table headers.

  Args:
    *args (str or tuple, optional): Variable length argument list. Must be composed of strings or
      tuples (of string and tuple of two ints).

      Tuple typed arguments must have a string as its first index element, and a
      tuple of two integers representing the column size for the header (md, xs).

  Examples:
    Using `table_headers` with no arguments.
    {% call table_headers() %}
      <th>First name</th>
      <th>Last name</th>
    {% endcall %}

    Using `table_headers` with strings.
    {% call table_headers("First name", "Last name") %}{% endcall %}

    Using `table_headers` with tuple arguments.
    {% call table_headers(("First name", (6, 6)), (("Last name"), (6, 6))) %}{% endcall %}

#}
{% macro table_headers() %}
  <thead>
    <tr>
      {% if varargs|length == 0 %}
        {{ caller() }}
      {% else %}
        {% for header in varargs %}
          {% if header is string %}
            <th>{{ header }}</th>
          {% elif header is sequence and header|length == 2 %}
            {% set header_text, colwidth = header %}
            {% set md, xs = colwidth %}
            <th class="col-md-{{ md }} col-xs-{{ xs }}">{{ header_text }}</th>
          {% endif %}
        {% endfor %}
      {% endif %}
    </tr>
  </thead>
{% endmacro %}


{# Renders an HTML table body. #}
{% macro table_rows() %}
  <tbody>
    {{ caller() }}
  </tbody>
{% endmacro %}


{# Renders an horizontal row.

  Note:
    It renders the row horizontally instead of vertically, like the following:
    --------------------------
    | Header |   `caller`    |
    --------------------------

  Args:
    header (str): The header column text.

#}
{% macro table_hrow(header, attr={}) %}
  <tr>
    <th {{ utils.attributes(attr, css_class="text-nowrap") }}>{{ header }}</th>
    {{ caller() }}
  </tr>
{% endmacro %}


{# Renders an horizontal row. The data defaults to `failure_text` if `attr`
    value is falsy or None.

  Args:
    data (obj): The attribute that is conditionally displayed in the row (if truthy).
    header (str): The header text.
    classes (dict, optional): The CSS classes applied to the <th>(`header` key) and <td>(`data` key) elements.
    failure_text (str, optional): The text displayed in the row, in case `attr`
      is falsy or None.

#}
{% set default_failure_text = _("Unknown") %}
{% macro conditional_hrow(data, header, columns=None, failure_text=default_failure_text) %}
  {% if columns is none %}
    {% set columns =  {"header": "col-md-3 col-xs-6", "data": "col-md-9 col-xs-6"} %}
  {% endif %}
  {% call table_hrow(header, {"class": columns.header}) %}
    <td class="{{ columns.data }}">{{ data|default(failure_text, true) }}</td>
  {% endcall %}
{% endmacro %}

app/templates/macros/utils.jinja2
{# The CSS class name used for activating macros/scripts' `momentjs_from_now`. #}
{% set timed = "__timed" %}


{# Renders inline HTML tag attributes.

  Args:
    attr (dict): The attributes with their value.
    css_class (str, optional): Space delimited CSS classes. Will be prepended to
      the attr `class` key-value.

  Example:
    <div {{ attributes({"id": "my-panel", "class": "panel-default"}, css_class="panel") }}></div>

    Will result in:
    <div id="my-panel" class="panel panel-default"></div>

#}
{% macro attributes(attr={}, css_class="") -%}
  {% set _class = css_class + " " + attr.class if attr.class else css_class %}
  {% do attr.update({"class": _class}) %}
  {%- for attribute, attribute_value in attr.iteritems() -%}
    {{- attribute -}}="{{- attribute_value -}}"
  {%- endfor -%}
{% endmacro %}


{# HTML data attribute for sorting column cells from datetime objects.

  Note:
    The table must be sorted using tablesort.js for this attribute
    to have any effect.

  Args:
    datetime (datetime object): The datetime object used for sorting.

#}
{% macro date_sort(datetime) -%}
  data-sort="{{ datetime|to_unix_timestamp|int }}"
{%- endmacro %}


app/templates/scripts/bootstrap.jinja2
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/templates/scripts/jquery.jinja2
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>

app/templates/styles/app.jinja2
<link href="{{ url_for("static", filename="styles/app.css") }}" rel="stylesheet"/>

app/templates/styles/bootstrap.jinja2
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

app/templates/styles/fontawesome.jinja2
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" charset="utf-8">